sudo: false

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sbt"
  - "$HOME/.ivy2"

language: scala

scala:
- 2.10.6

jdk:
- oraclejdk7

sbt_args: "-no-colors -J-Xss2m"

script: sbt -Dsbt.log.noformat=true +test

notifications:
  email:
  - kxie@krux.com
  - seth.yates@krux.com

before_install:
- |
  if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_d039d4b3556d_key -iv $encrypted_d039d4b3556d_iv -in pubring.gpg.enc -out pubring.gpg -d
    openssl aes-256-cbc -K $encrypted_d039d4b3556d_key -iv $encrypted_d039d4b3556d_iv -in secring.gpg.enc -out secring.gpg -d
  fi

after_success:
- |
  if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    sbt 'set pgpPassphrase := Some(System.getenv("PGP_PASSPHRASE").toCharArray)' 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USERNAME"), System.getenv("SONATYPE_PASSWORD"))' +publishSigned sonatypeReleaseAll
    rm -f secring.gpg pubring.gpg
  fi

env:
  global:
  - secure: RtKl8w+K8yNH6APVQeU+GofhTSFRn3h1lESYTaMpTdccMAnyAP6Msdfe7J+u2z4GFeSKODCpM4mTIbxT5ObDTvcfWYrinXC/7JGDTzrhCjF0Er684zROwhDjf4pEGUm7q0TaxrUJW6d4psSM+B29VkVK/bNzS8hdCwLPVE1p50Tvqwk9v0W/5uwBXAzTAiXhhJ8CP+TTUpNlJtfD0vJJuPdxhI3wlG3NLYbag2BNzC0Y0B9pV2SmiralJrqX1IsIcBLRdB5GpPGiheQzN9lkm6THKR/+LVq1ps9YIiDb22fsb4rQHxMx8UjuaL+VDzjzsg4LpsZlZskPW4FjxaV6ohKrSeJ/9KKf0dELtyQ3EXnSIJvhugeGbpoU1WPkmlLw8GHLgAy2eUfm3FmabFcXKbJpUZLfFGX7iJ/XxbsXBT2YbwidBa91qf0y+svxT957BLJg5CCnJswV1+a9lT2O2Z6WxJhBvQ1vaETpNZvW8uFT4V81ZBXrgbqDHpCyTlnKVyEu1aRkKis2oAxEGR8iWazlzoIs1ehK7HaKJihBMKzS8DNzQ9bDxmbUfawC4VwFs+q93/MlRgNW5hFjexSO/525EGV6epy/HS12GANxFzFQes7eeulb+7XkhEFzTkDgsHRLXxcetlfGMUblwbvAhBxL6Ex+LUnL8SNje+78V6I=
  - secure: G2bzj75camKqv3yFHo+8jRFsSYiz/QVDEIm68UNWh5FyWL6jIzFgAMnCSbGlxGC4kpbHvhF9Ael+RAlRWI8gihahyBcbU3TiquaFCaqCmBCeQjbnFAhOmQ6hK1yjAAPFih9keRO19L8Zg7eunUFVd4U33oylcUO5b+wLg3lOjs+uq02SEuoFnJz34R6e+TtkTSkUdDTspNY56DPdvLJON8RYLIT7k5OICEt+EvxEkqimQvxaER8PM1RyVYsuVwgARpbsSWsnyyMnfaxMnDpoCr4DwlQiuSrYm14BVHPJVe1Q0+qU1ye8o+1dxDfAgwVe3sN0DBPNQ50DTOt6wahw+bf6K4RFCn+Ot0zYxsDxFK/fV8HfYohqotQjGvswXKLkrrQfX9YcfE6Q/Jf97SDBavLOU7xhLKwjvLc0uGhuewkz8wl+jOt3PqcDu2fRWSIjx4Ar9JfHtyZNrpa0jerzjPyF2eInjx3IbJlMA23y/wPmi7TJCwIKggeVq6KXtc6+Dmzn4gpGXTPqdiWrzMrpG7S81PxIagjxJ1Hq8cund5qIBIqmrxa2svQ/ZfYe43XnBYaKScVcGZDgGM2fXU8I5iyJOsd3HpkZMaH3HDGqF01Nu2P2lBWNv9Qj/NkLf4hL+wT3Wbbsv9kNMMYOyod/DxgyzQEra4Vef9UiajID/X4=
  - secure: AxTEka4NpZntU5/C1ldGwi7eo5BrlvpWX8+7ueIPub+fRMe5AT0vYcNiaHLRXfOVuC1P5HlZNMYtUXSlwRnkgn/81zRWTpaMP5u81WfVHxfwLnf5gEVmfD8vi1e6urMHCoQ8KWXMnQE/hXgPSiylNBYrPRCJWlyRjm4Yz8vPyQj8tbnLBrc/EChHYn1ZTAJ2Xkn8/vkR4EnlOgd/Jy1EAmV3BkLAYmeLdD88h8R+Nj57BeLpwtrnOzErtjcKAFDX6Z7esbCkjh91sc8tWyP/4O8xCg33vRLW8Vt+TObndmZ7k/k0PiitRPvmQmVkWdaSe7YS09J8Z9rLN1/SkQ5A3WTIi7+/sb53K/ff3u5KwucbgjLgFTKq8JKrJxUPoyV6xdNu1hl9NEkzn6XG3+xMoGHL/yGJLTTkjgjnkcRSoc5Xcv9lHOfI6a1x1MGlfJXNiiLs2Rdyjl7zyVXnxrlZTc3kRF3fEAtHQIi+1KCZimEgmCNwHwl2tipgFeGgR8C+9Vj+fwNAQXnNfhgsu3q/fcYG+5kybR5PZxVGEZ7USPVKMiAd6yfgJjU1UeN/d6+GwkfB0ffBoHFl7CMuFJeWLlVmnpxd6KO0RGJiYN/bFadu7zTmeKPrToSxpqCCFAbN11yOkluKuzLBlIzhHsWwK00MiN/edT1a9Cha8i9g/uk=
