sudo: false

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sbt
  - $HOME/.ivy2

language: scala

scala:
- 2.10.6

jdk:
- oraclejdk7

sbt_args: -no-colors -J-Xss2m

script: sbt -Dsbt.log.noformat=true +test

notifications:
  email:
  - kxie@krux.com
  - seth.yates@krux.com
